lego_attachment_show:
    path: /show
    controller: lego.attachment.action.show

lego_attachment_delete:
    path: /{id}/delete
    controller: lego.attachment.action.delete
    methods: [POST]

lego_attachment_upload:
    path: /upload
    controller: lego.attachment.action.upload

lego_attachment_download:
    path: /{id}/download
    controller: lego.attachment.action.download

lego_attachment_thumb:
    path: /{id}/thumb
    controller: lego.attachment.action.thumb